version: "3.9"

services:
  api:
    image: om101004/medflowai-api:v2.3-AMD64
    container_name: medflowai-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ml-service

  client:
    image: om101004/medflowai-frontend:v2.7-AMD64
    container_name: medflowai-client
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - api
      - ml-service

  ml-service:
    image: om101004/medflowai-ml_service:v1.4-AMD64
    container_name: medflowai-ml-service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
